/* eslint-disable react/prop-types */
import  { useEffect } from 'react';
import { common, createLowlight } from 'lowlight';
import './BlogPreview.css';

// Create a lowlight instance with common languages
const lowlight = createLowlight(common);

// Import additional languages
import javascript from 'highlight.js/lib/languages/javascript';
import html from 'highlight.js/lib/languages/xml';
import css from 'highlight.js/lib/languages/css';
import java from 'highlight.js/lib/languages/java';
import python from 'highlight.js/lib/languages/python';
import php from 'highlight.js/lib/languages/php';

// Register languages
lowlight.register('javascript', javascript);
lowlight.register('html', html);
lowlight.register('css', css);
lowlight.register('java', java);
lowlight.register('python', python);
lowlight.register('php', php);

const BlogPreview = ({ content }) => {
  useEffect(() => {
    // Select all code blocks in the preview
    const codeBlocks = document.querySelectorAll('.blog-preview pre code');
    
    codeBlocks.forEach(block => {
      // Get the language from the class attribute (language-xxx)
      const classNames = block.className.split(' ');
      const languageClass = classNames.find(className => className.startsWith('language-'));
      const language = languageClass ? languageClass.replace('language-', '') : 'javascript';
      
      try {
        // Apply syntax highlighting with lowlight
        const result = lowlight.highlight(language, block.textContent);
        
        // Replace the block content with the HTML generated by lowlight
        let html = '';
        result.children.forEach(node => {
          if (node.type === 'element') {
            html += `<span class="${node.properties.className.join(' ')}">${node.children[0].value}</span>`;
          } else if (node.type === 'text') {
            html += node.value;
          }
        });
        
        block.innerHTML = html;
      } catch (error) {
        console.error(`Error during syntax highlighting for ${language}:`, error);
      }
    });
  }, [content]);

  return (
    <div className="blog-preview">
      <div className="blog-content" dangerouslySetInnerHTML={{ __html: content }} />
    </div>
  );
};

export default BlogPreview;